CREATE TABLE [Boying_Framework_CultureRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,[Culture] [nvarchar](255) NULL);
CREATE TABLE [Boying_Framework_DataMigrationRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,[DataMigrationClass] [nvarchar](255) NULL,[Version] [int] NULL);
CREATE TABLE [Boying_Framework_DistributedLockRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,[Name] [nvarchar](512) NOT NULL,[MachineName] [nvarchar](256) NULL,[CreatedUtc] [datetime] NULL,[ValidUntilUtc] [datetime] NULL);
CREATE TABLE [Scheduling_ScheduledTaskRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY,[TaskType] [nvarchar](255) NULL,[ScheduledUtc] [datetime] NULL,[ContentItemVersionRecord_id] [int] NULL);
CREATE TABLE [Settings_ShellDescriptorRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,[SerialNumber] [int] NULL);
CREATE TABLE [Settings_ShellFeatureRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,[Name] [nvarchar](255) NULL,[ShellDescriptorRecord_id] [int] NULL);
CREATE TABLE [Settings_ShellFeatureStateRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,[Name] [nvarchar](255) NULL,[InstallState] [nvarchar](255) NULL,[EnableState] [nvarchar](255) NULL,[ShellStateRecord_Id] [int] NULL);
CREATE TABLE [Settings_ShellParameterRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,[Component] [nvarchar](255) NULL,[Name] [nvarchar](255) NULL,[Value] [nvarchar](255) NULL,[ShellDescriptorRecord_id] [int] NULL);
CREATE TABLE [Settings_ShellStateRecord]([Id] [int] IDENTITY(1,1) NOT NULL PRIMARY KEY ,[Unused] [nvarchar](255) NULL);
INSERT [Boying_Framework_CultureRecord] ([Culture]) VALUES (N'zh-CN');
INSERT [Boying_Framework_DataMigrationRecord] ([DataMigrationClass], [Version]) VALUES (N'Boying.Core.Settings.Migrations', 5);
INSERT [Boying_Framework_DataMigrationRecord] ([DataMigrationClass], [Version]) VALUES (N'Boying.Recipes.Migrations', 1);
INSERT [Boying_Framework_DataMigrationRecord] ([DataMigrationClass], [Version]) VALUES (N'Boying.Themes.ThemesDataMigration', 2);
INSERT [Settings_ShellDescriptorRecord] ([SerialNumber]) VALUES (1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'Boying.Framework', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'Settings', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'Boying.Themes', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'Boying.Modules', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'Boying.CodeGeneration', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'Shapes', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'VuLu', 1);
INSERT [Settings_ShellFeatureRecord] ([Name], [ShellDescriptorRecord_id]) VALUES (N'TheThemeMachine', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'Settings', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'Shapes', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'Boying.Themes', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'Boying.Modules', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'Boying.CodeGeneration', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'VuLu', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'TheThemeMachine', N'Up', N'Up', 1);
INSERT [Settings_ShellFeatureStateRecord] ([Name], [InstallState], [EnableState], [ShellStateRecord_Id]) VALUES (N'Boying.Main', N'Up', N'Down', 1);
INSERT [Settings_ShellStateRecord] ([Unused]) VALUES (NULL);
ALTER TABLE [Boying_Framework_CultureRecord] ADD  CONSTRAINT [UC_CR_Name] UNIQUE NONCLUSTERED ([Culture] ASC);
ALTER TABLE [Boying_Framework_DataMigrationRecord] ADD  CONSTRAINT [UC_DMR_DataMigrationClass_Version] UNIQUE NONCLUSTERED ([DataMigrationClass] ASC,[Version] ASC);
ALTER TABLE [Boying_Framework_DistributedLockRecord] ADD UNIQUE NONCLUSTERED ([Name] ASC);
ALTER TABLE [Settings_ShellFeatureStateRecord] ADD  CONSTRAINT [UC_SFSR_SSRId_Name] UNIQUE NONCLUSTERED ([ShellStateRecord_Id] ASC,[Name] ASC);
ALTER TABLE [Settings_ShellParameterRecord] ADD  CONSTRAINT [UC_SPR_SDRId_Component_Name] UNIQUE NONCLUSTERED ([ShellDescriptorRecord_id] ASC,[Component] ASC,[Name] ASC);